#!/bin/bash

VALARM_NAME=valarm
VALARM_VER=0.0.3

MUSIC_PATH=/home/pi/music/
DI_URL=http://listen.di.fm/public3/
LUB_URL=http://rzg.pl/player/

nofit_cnt=0

function valarm_usage {
    echo Usage:$VALARM_NAME '<time>' '<music type>'
    if [ -n "$1" ]; then
	exit "$1"
    fi
}

function valarm_play_music {

    case $2 in
	di)
	    (sleep $1; mplayer -playlist $DI_URL$3.pls > /dev/null 2>&1) &
	    ;;

	lub)
	    (sleep $1; mplayer -playlist $LUB_URL$3.m3u > /dev/null 2>&1) &
	    ;;

	mp3)
	    (sleep $1; mplayer $MUSIC_PATH*$3* > /dev/null 2>&1) &
            ;;

	*)
	    valarm_usage -3
	    ;;
    esac
	
}

if [ -z "$1" ];
then
    valarm_usage -1
fi

for i in $@; do
    case $i in
	--version)
	    echo $VALARM_NAME $VALARM_VER
	    echo Copyright '(C)' 2013 SEITAZ
	    echo License GPLv3+: GNU GPL version 3 or later '<http://gnu.org/licenses/gpl.html>'
	    echo This is free software: you are free to change and redistribute it.
	    echo There is NO WARRANTY, to the extent permitted by law.
	    exit 0
	    ;;
	--help)
	    valarm_usage
	    echo Report bugs to: '<http://github.com/voslak/valarm/issues>'
	    echo $VALARM_NAME home page: '<http://github.com/voslak/valarm>'
	    echo General help using GNU software: '<http://www.gnu.org/gethelp/>'
	    exit 0
	    ;;
	*)
	    let nofit_cnt++
    	    ;;
    esac
done
 
sec_future=$(date -d "$1" +%s)
sec_now=$(date +%s)
((sec_sleep = $sec_future - $sec_now))

if [ "$sec_sleep" -le -1 ]
then
    ((sec_sleep = $sec_sleep +(60*60*24)))
fi

case $2 in
    trance)      ;&
    vocaltrance) ;&
    chillout)    ;&
    house)       ;&
    electro)
	valarm_play_music $sec_sleep di $2
	;;

    rzg) ;&
    rz)  ;&
    rg)
	valarm_play_music $sec_sleep lub $2
	;;

    *)
	valarm_play_music $sec_sleep mp3 $2
	;;
esac

echo ======================================================
echo $2 will wake you up $(date -d "$1")!
echo "Exiting."
echo ======================================================

exit 0

